security:
  encoders:
    App\Entity\User: bcrypt

  providers:
    database_users:
      entity: { class: App\Entity\User, property: email }

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      pattern: ^/
      anonymous: true
      json_login:
        check_path: /api/login
      logout:
        # The route name the user can go to in order to logout
        path: api_logout
        # The name of the route to redirect to after logging out
        target: index
